# Generated by Django 4.0 on 2022-12-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0005_project_delete_course_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
