# Generated by Django 4.0 on 2022-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0008_alter_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
