# Generated by Django 4.0 on 2023-01-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0017_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preamble',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
