# Generated by Django 4.0 on 2023-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0018_alter_article_preamble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
