# Generated by Django 4.0 on 2023-01-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0019_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
