# Generated by Django 4.0 on 2023-01-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0020_alter_article_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
