# Generated by Django 4.0 on 2023-01-20 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0021_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('bio', models.CharField(max_length=75, null=True)),
                ('profile', models.ImageField(null=True, upload_to='Images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
