# Generated by Django 4.0 on 2023-01-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0022_user_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
