# Generated by Django 4.2.3 on 2023-08-24 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0024_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20, unique=True)),
                ('price', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=75, null=True)),
                ('description', models.CharField(max_length=75, null=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('profile', models.ImageField(null=True, upload_to='Images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
