# Generated by Django 4.2.3 on 2023-08-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0027_categorie_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='name',
            new_name='categor_name',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='slug',
        ),
    ]
