# Generated by Django 4.2.3 on 2023-08-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0028_rename_name_categorie_categor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='categor_name',
            new_name='name',
        ),
    ]
