# Generated by Django 4.2.3 on 2023-08-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0030_product_alter_categorie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
