# Generated by Django 4.2.3 on 2023-09-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0031_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
