# Generated by Django 4.2.3 on 2023-09-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0032_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
