# Generated by Django 4.2.3 on 2023-09-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0033_product_likes_alter_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
