# Generated by Django 4.2.3 on 2023-09-07 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0034_remove_product_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=90, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('likes', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='Images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1)),
            ],
        ),
    ]
