# Generated by Django 4.2.3 on 2023-09-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0036_cart_count_alter_cart_likes_alter_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=90, null=True),
        ),
    ]
