# Generated by Django 4.2.3 on 2023-09-08 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0037_remove_cart_count_alter_cart_name_alter_cart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
